extn: .png
epochs: 300
in_width: 384
in_height: 288
model_path: models/model1.pth
log_path: models/logs/logs.csv
image_path: input/PNG/Original
mask_path: input/PNG/Ground Truth
output_path: output/prediction.png